bookings/urls.py
from django.urls import path
from . import views

app_name = 'booking'

urlpatterns = [
    path('', views.booking_form, name='booking_form'),
]

dates/urls.py
from django.urls import path
from . import views

app_name = 'dates'
urlpatterns = [
]

enquiries/urls.py
from django.urls import path
from . import views

app_name = 'enquiry'

urlpatterns = [
    path('', views.enquiry_form, name='enquiry_form'),
]

three_amigos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from bookings import views
from dates import views
from enquiries import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.get_index, name='index'),
    path('base/', views.get_base, name='base'),
    path('dates/', views.get_dates, name='dates'),
    path('results/', views.get_results, name='results'),
    path('info/', views.get_info, name='info'), 
    path('bookings/', include('bookings.urls', namespace="bookings")),
    path('enquiry/', include('enquiries.urls', namespace="enquiry")),
    path('dates/', include('dates.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'bookings.views.error_404'

bookings/models.py
from django.db import models
from django.utils import timezone

OCCASIONS = (
    ('AW','After Work'),
    ('KO','Work Kick Off'),
    ('BP','Birthday Party'),
    ('SP','Surprise Party'),
    ('O','Other'),
)

THEMES = (
    ('TAQ','Three Amigos Quiz'),
    ('ST','Specific/Themed Quiz'),
)

LOCATIONS = (
    ('TS','The Snug (12-20ppl)'),
    ('WP','Wirströms Pub (20-100ppl)'),
    ('W','At your workplace'),
    ('OL','Other Location'),
)

class Booking(models.Model):
    booking_id = models.AutoField(primary_key=True)
    booking_name = models.CharField(max_length=150, blank= False)
    booking_email = models.EmailField(max_length=150, blank= False)
    booking_company = models.CharField(max_length=150)
    booking_occasion = models.CharField(
        max_length=30,
        choices=OCCASIONS,
        blank= False,
        )
    booking_theme = models.CharField(
        max_length=20,
        choices=THEMES,
        blank= False,
    )
    booking_location = models.CharField(
        max_length=30,
        choices=LOCATIONS,
        blank= False,
    )
    booking_number_of_quizzers = models.IntegerField(blank= False)
    booking_when = models.DateTimeField(default=timezone.now, blank= False)
    booking_information = models.TextField(max_length=1000, blank=True)
    booking_sent = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Booking #{self.booking_id} - Name {self.booking_name} - Email {self.booking_email}"

dates/models.py
from django.db import models

# Create your models here.

enquiries/models.py
from django.db import models
from django.utils import timezone


class Enquiry(models.Model):
    OCCASIONS = (
        ('AW','After Work'),
        ('KO','Work Kick Off'),
        ('BP','Birthday Party'),
        ('SP','Surprise Party'),
        ('O','Other'),
    )

    THEMES = (
        ('TAQ','Three Amigos Quiz'),
        ('ST','Specific/Themed Quiz'),
    )

    LOCATIONS = (
        ('TS','The Snug (12-20ppl)'),
        ('WP','Wirströms Pub (20-100ppl)'),
        ('W','At your workplace'),
        ('OL','Other Location'),
    )

    enquiry_id = models.AutoField(primary_key=True)
    enquiry_name = models.CharField(max_length=150, blank= False)
    enquiry_email = models.EmailField(max_length=150, blank=False)
    enquiry_company = models.CharField(max_length=150, blank=True)
    enquiry_occasion = models.CharField(
        max_length=30,
        choices=OCCASIONS,
        blank=True,
        )
    enquiry_theme = models.CharField(
        max_length=20,
        choices=THEMES,
        blank=True,
    )
    enquiry_location = models.CharField(
        max_length=30,
        choices=LOCATIONS,
        blank=True,
    )
    enquiry_number_of_quizzers = models.IntegerField(blank=True, null=True)
    enquiry_when = models.DateTimeField(default=timezone.now, null=False)
    enquiry_information = models.TextField(max_length=1000, blank=True)
    enquiry_sent = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Booking #{self.enquiry_id} - Name {self.enquiry_name} - Email {self.enquiry_email}"

bookings/forms.py
from django import forms
from .models import Booking


class BookingForm(forms.ModelForm):
    booking_when = forms.DateTimeField(
        widget=forms.DateTimeInput(
            format='%Y-%m-%dT%H:%M',
            attrs={'type': 'datetime-local'}
        ),
        label="Date and Time"
    )

    OCCASIONS = (
        ('AW','After Work'),
        ('KO','Work Kick Off'),
        ('BP','Birthday Party'),
        ('SP','Surprise Party'),
        ('O','Other'),
    )

    THEMES = (
        ('TAQ','Three Amigos Quiz'),
        ('ST','Specific/Themed Quiz'),
    )

    LOCATIONS = (
        ('TS','The Snug (12-20ppl)'),
        ('WP','Wirströms Pub (25-100ppl)'),
        ('W','At your workplace'),
        ('OL','Other Location'),
    )


    class Meta:
        model = Booking
        fields = [
            'booking_name', 'booking_email', 'booking_company', 'booking_occasion',
            'booking_theme', 'booking_number_of_quizzers', 'booking_location', 
            'booking_when', 'booking_information']

enquiries/forms.py
from django import forms
from .models import Enquiry


class EnquiryForm(forms.ModelForm):
    enquiry_when = forms.DateTimeField(
        widget=forms.DateTimeInput(
            format='%Y-%m-%dT%H:%M',
            attrs={'type': 'datetime-local'}
        ),
        label="Preferred Date and Time"
    )

    OCCASIONS = (
        ('AW','After Work'),
        ('KO','Work Kick Off'),
        ('BP','Birthday Party'),
        ('SP','Surprise Party'),
        ('O','Other'),
    )

    THEMES = (
        ('TAQ','Three Amigos Quiz'),
        ('ST','Specific/Themed Quiz'),
    )

    LOCATIONS = (
        ('TS','The Snug (12-20ppl)'),
        ('WP','Wirströms Pub (25-100ppl)'),
        ('W','At your workplace'),
        ('OL','Other Location'),
    )


    class Meta:
        model = Enquiry
        fields = [
            'enquiry_name', 'enquiry_email', 'enquiry_company', 'enquiry_occasion',
            'enquiry_theme', 'enquiry_number_of_quizzers', 'enquiry_location', 
            'enquiry_when', 'enquiry_information']

bookings/views.py
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from .forms import BookingForm

# Create your views here.

def get_index(request):
    return render(request, 'index.html')

def get_base(request):
    return render(request, 'base.html')

def get_dates(request):
    return render(request, 'dates.html')

def get_results(request):
    return render(request, 'results.html')

def get_info(request):
    return render(request, 'info.html')

def get_enquiry(request):
    return render(request, 'enquiry.html')

def error_404(request, exception):
    return render(request, '404.html')

def booking_form(request):
    if request.method == "POST":
        form = BookingForm(request.POST)

        if form.is_valid():
            booking = form.save()

            subject = f"New Booking from {booking.booking_name}"
            message = f"""
            Enquiry Details:
            ID: {booking.booking_id}
            Name: {booking.booking_name}
            Email: {booking.booking_email}
            Occasion: {booking.booking_occasion}
            Location: {booking.booking_location}
            Theme: {booking.booking_theme}
            Date & Time: {booking.booking_when}
            Additional Info: {booking.booking_information}
            """
            recipient = settings.EMAIL_HOST_USER
            send_mail(subject, message, settings.EMAIL_HOST_USER, [recipient])

            messages.success(request, "Thank you for your enquiry! We should soon receive a reply from threeamigosquiz@gmail.com ")
            return redirect('booking:booking_form')

        else:
            messages.error(request, "Please fill in the required fields")
            return render(request, 'booking_form.html', {'form': form})
    
    else:
        form = BookingForm()

    return render(request, 'booking_form.html', {'form': form})

dates/views.py
from django.shortcuts import render
from .services import get_sheet_upcoming_dates
from .services import get_sheet_past_results

# Create your views here.

def get_dates(request):
    return render(request, 'dates.html')

def get_results(request):
    return render(request, 'results.html')

def get_info(request):
    return render(request, 'info.html')

def get_index(request):
    return render(request, 'index.html')

def get_base(request):
    return render(request, 'base.html')

def upcoming_dates(request):
    api_id = 'fvi6b7rkv2z2b'
    tab_name = 'upcoming_quizzes'
    sheet_data = get_sheet_upcoming_dates(api_id)

    return render(request, 'dates.html', {'sheet_data': sheet_data})

def past_results(request):
    api_id = 'fvi6b7rkv2z2b'
    tab_name = 'past_quizzes_normal'
    sheet_data = get_sheet_past_results(api_id)

    return render(request, 'results.html', {'sheet_data': sheet_data})

enquiries/views.py
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from .forms import EnquiryForm

# Create your views here.

def get_index(request):
    return render(request, 'index.html')

def get_base(request):
    return render(request, 'base.html')

def get_dates(request):
    return render(request, 'dates.html')

def get_results(request):
    return render(request, 'results.html')

def get_info(request):
    return render(request, 'info.html')

def get_enquiry(request):
    return render(request, 'enquiry.html')

def error_404(request, exception):
    return render(request, '404.html')

def enquiry_form(request):
    if request.method == "POST":
        form = EnquiryForm(request.POST)

        if form.is_valid():
            enquiry = form.save()

            subject = f"New Enquiry from {enquiry.enquiry_name}"
            message = f"""
            Enquiry Details:
            ID: {enquiry.enquiry_id}
            Name: {enquiry.enquiry_name}
            Email: {enquiry.enquiry_email}
            Occasion: {enquiry.enquiry_occasion}
            Location: {enquiry.enquiry_location}
            Theme: {enquiry.enquiry_theme}
            Date & Time: {enquiry.enquiry_when}
            Additional Info: {enquiry.enquiry_information}
            """
            recipient = settings.EMAIL_HOST_USER
            send_mail(subject, message, settings.EMAIL_HOST_USER, [recipient])

            messages.success(request, "Thank you for your enquiry! We should soon receive a reply from threeamigosquiz@gmail.com ")
            return redirect('enquiry:enquiry_form')

        else:
            messages.error(request, "Please fill in the required fields")
            return render(request, 'enquiry_form.html', {'form': form})
    
    else:
        form = EnquiryForm()

    return render(request, 'enquiry_form.html', {'form': form})

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% url 'index' as index_url %}

<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">

    <title>{% block head_title %}Three Amigos Quiz page{% endblock %}</title>
    {% load static %}
    <meta content="One of Stockholm's oldest quiz team" name="description" />
    <meta content="AW Stockholm, aw, gamla stan, quiz, aw quiz, Stockholm quiz, pub quiz" name="keywords" />

    <!-- Favicons -->
    <link rel="icon" href="{% static 'media/favicon.ico' %}" />
    <link rel="apple-touch-icon" href="{% static 'media/apple-touch-icon.png' %}" />

    <!-- FontAwesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=BioRhyme:wght@200..800&family=Cabin:ital,wght@0,400..700;1,400..700&display=swap"
        rel="stylesheet">

    <!-- Template Main CSS File -->
     <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Flatpickr CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/themes/material_green.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

</head>

<body>
    <!-- ===== Header ===== -->
    <header id="header" class="fixed-top align-items-center">
    <!-- Navbar -->
        <nav id="navbar" class="navbar order-last order-lg-0">
            <ul class="navbar ml-auto ">
                <li>
                    <a href="{% url 'index' %}">
                        <img src="{% static '/media/index-images/ta-logo-9E7442.png' %}" id=logo alt="Three Amigos Logo" />
                    </a>
                </li>
                <li class="nav-item dropdown d-lg-none">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                    Go to
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'index' %}#intro">Home</a></li>
                        <li><a class="dropdown-item" href="{% url 'dates' %}#dates">Dates</a></li>
                        <li><a class="dropdown-item" href="{% url 'results' %}#results">Results</a></li>
                        <li><a class="dropdown-item" href="{% url 'booking:booking_form' %}#booking">Book</a></li>
                        <li><a class="dropdown-item" href="{% url 'enquiry:enquiry_form' %}#enquiry">Enquiry</a></li>
                        <li><a class="dropdown-item" href="{% url 'info' %}#info">Quiz Info</a></li>
                        <li><a class="dropdown-item" href="https://wirstromspub.se#wirstroms" target="_blank">Wirströms Pub</a></li>
                    </ul>
                </li>
                <li>
                    <a class="nav-link d-none d-lg-block" href="{% url 'index' %}#intro">Home</a>
                </li>
                <li>
                    <a class="nav-link d-none d-lg-block" href="{% url 'dates' %}#dates">Dates</a>
                </li>
                <li>
                    <a class="nav-link d-none d-lg-block" href="{% url 'results' %}#results">Results</a>
                </li>
                <li>
                    <a class="nav-link d-none d-lg-block" href="{% url 'booking:booking_form' %}#book">Book</a>
                </li>
                <li>
                    <a class="nav-link d-none d-lg-block" href="{% url 'enquiry:enquiry_form' %}#enquiry">Enquiry</a>
                </li>
                <li>
                    <a class="nav-link d-none d-lg-block" href="{% url 'info' %}#info">Info</a>
                </li>
                <li>
                    <a class="nav-link d-none d-lg-block" href="https://wirstromspub.se#wirstroms" target="_blank">Wirströms Pub</a>
                </li>
            </ul>
        </nav>
    </header>

    <main>

        <!-- Messages -->
        {% if messages %}
            <div id="info-messages">
                {% for message in messages %}
                    <div class="message {{ message.tags}}">
                        {{ message }}
                        <button class="close-message-btn"><i class="fa fa-times-circle" aria-hidden="true"></i></button>
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        {% block content %}
        <!-- Main content goes here -->
        {% endblock content %}

    </main>

    <!-- ===== Main Footer ===== -->
     <footer id="footer" class="footer"
        <div class="container">
            <div class="copyright">
                &copy; Copyright {% now 'Y' %}
                <strong><span>Dan Roberts</span></strong>. All Rights Reserved
            </div>
        </div>
    </footer>
    <!-- End Footer -->

    <!-- Template Main JS File -->
    <script src="{% static 'js/main.js' %}"></script>

    <!-- jQuery first, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous">
    </script>

    <!-- Messages JS function -->
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            document.querySelectorAll(".close-message-btn").forEach (function (btn) {
                btn.addEventListener("click", function () {
                    const message = this.parentElement;
                    message.style.opacity = 0;
                    setTimeout(function() {
                        message.style.display = "none";
                    }, 200);
                });
            });
        });
    </script>

</body>

</html>

templates/booking.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- ===== Booking Section ===== -->
<section id="booking">
    <div class="container">
        {% include 'booking:booking_form.html' %}
    </div>
</section>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const clearButton = document.getElementById('btn-clear');
        if (clearButton) {
            clearButton.addEventListener('click', function () {
                // Reset the form fields
                document.getElementById('booking-form').reset();
            });
        }
    });
</script>

{% endblock %}

templates/booking_form.html
{% extends "booking.html" %}
{% block content %}

<div id="booking">
    <form id="booking-form" action="{% url 'booking:booking_form' %}" method="post">
        {% csrf_token %}
        <h1>Booking Form</h1>
        <h5>Required fields in BOLD</h5>
        <div class="form-group row g-3 d-flex justify-content-center">
            <div class="col-md-6">
                <label for="id_booking_name" class="form-label">NAME:</label>
                <input type="text" class="form-control" id="id_booking_name" name="booking_name"
                    placeholder="*Required*">
            </div>
            <div class="col-md-6">
                <label for="id_booking_email" class="form-label">EMAIL:</label>
                <input type="email" class="form-control" id="id_booking_email" name="booking_email"
                    placeholder="*Required*">
            </div>
            <div class="col-md-6">
                <label for="id_booking_company" class="form-label">Company:</label>
                <input type="text" class="form-control" id="id_booking_company" name="booking_company">
            </div>
            <div class="col-md-6">
                <label for="id_booking_occasion" size="5" class="form-label">OCCASION:</label>
                <select id="id_booking_occasion" class="form-select" name="booking_occasion" placeholder="*Required*">
                    {% for selection, choice in form.booking_occasion.field.choices %}
                    <option value="{{ selection }}">{{ choice }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-6">
                <label for="id_booking_location" size="4" class="form-label">LOCATION:</label>
                <select id="id_booking_location" class="form-select" name="booking_location">
                    {% for selection, choice in form.booking_location.field.choices %}
                    <option value="{{ selection }}">{{ choice }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-6">
                <label for="id_booking_theme" size="2" class="form-label">THEME:</label>
                <select id="id_booking_theme" class="form-select" name="booking_theme">
                    {% for selection, choice in form.booking_theme.field.choices %}
                    <option value="{{ selection }}">{{ choice }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-8">
                <label for="id_booking_when" class="form-label">DATE & TIME:</label>
                <input type="datetime-local" class="form-control" id="id_booking_when" name="booking_when"
                    placeholder="*Required - Choose preferred date & time">
            </div>
            <div class="range col-md-8">
                <label for="id_booking_number_of_quizzers" class="form-label" step="any">
                    NUMBER OF PARTICIPANTS:
                    <div class="slider-value" id="range-value">Use the slider to choose a number</div>
                </label>
                <input type="range" class="form-range" min="15" max="120" value="15" step="1"
                    id="id_booking_number_of_quizzers" name="booking_number_of_quizzers">
            </div>
            <div class="col-md-8">
                <label for="id_booking_description" class="form-label">Description:</label>
                <textarea class="form-control" id="id_booking_description" rows="5" name="booking_description"
                    placeholder="Please add any extra information here (max 1000 characters)">
                </textarea>
            </div>
            <div class="booking-btns col-6">
                <button type="reset" class="btn-clear">Clear Form</button>
                <button type="submit" class="btn-send">Send Enquiry</button>
            </div>
        </div>
        <div class="form-errors">
            {% if error %}
            <p class="error">{{ form.field_name.errors }}</p>
            {% endif %}
        </div>
    </form>
</div>

<script>
    const rangeInput = document.getElementById('id_booking_number_of_quizzers');
    const rangeValue = document.getElementById('range-value');

    rangeInput.addEventListener('input', function () {
        rangeValue.textContent = rangeInput.value;
    });
</script>
<script>
    flatpickr("#id_booking_when", {
        enableTime: true,
        time_24hr: true,
        minuteIncrement: 15,
        minDate: "today",
        minTime: "12:00",
        maxTime: "22:00",
        dateFormat: "Y-m-d\\TH:i",
    });
</script>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const locationLimit = document.getElementById("id_booking_location");
        const slider = document.getElementById("id_booking_number_of_quizzers");

        const setLimits = {
            "TS": { min: 12, max: 20 },
            "WP": { min: 20, max: 100 },
        };

        locationLimit.addEventListener("change", function () {
            const selectedLocation = this.value;
            const limits = setLimits[selectedLocation];

            if (limits) {
                slider.min = limits.min;
                slider.max = limits.max;

                if (slider.value < limits.min || slider.value > limits.max) {
                    slider.value = limits.min;
                }
            } else {
                slider.min = 10;
                slider.max = 150;
                slider.value = 10;
            }
        });
    });
</script>

{% endblock %}

templates/dates.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <!-- ===== Upcoming Quizzes Section ===== -->
    <section id="upcoming">
        <h1>Upcoming Quizzes</h1>
        <div class="container">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                    <button class="nav-link active" id="gs-tab" data-bs-toggle="tab" data-bs-target="#gs" type="button"
                        role="tab" aria-controls="gs" aria-selected="true">Wirströms Pub - Gamla Stan</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="city-tab" data-bs-toggle="tab" data-bs-target="#city" type="button"
                        role="tab" aria-controls="city" aria-selected="false">Wirströms City - Kungsgatan 5</button>
                </li>
            </ul>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="gs" role="tabpanel" aria-labelledby="gs-tab">
                    <table class="table text-center mt-3">
                        <thead>
                            <tr class="font-weight-bold">
                                <th scope="col" class="col-1">Date</th>
                            </tr>
                        </thead>
                        <tbody id="gs-dates-list"></tbody>
                    </table>
                </div>
                <div class="tab-pane fade" id="city" role="tabpanel" aria-labelledby="city-tab">
                    <table class="table text-center mt-3">
                        <thead>
                            <tr class="font-weight-bold">
                                <th scope="col" class="col-1">Date</th>
                            </tr>
                        </thead>
                        <tbody id="city-dates-list"></tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/enquiry_form.html
{% extends "enquiry.html" %}
{% block content %}

<div id="enquiry">
    <form id="enquiry-form" action="{% url 'enquiry:enquiry_form' %}" method="post">
        {% csrf_token %}
        <h1>Enquiry Form</h1>
        <h5>Required fields in BOLD</h5>
        <div class="form-group row g-3 d-flex justify-content-center">
            <div class="col-md-6">
                <label for="id_enquiry_name" class="form-label">NAME:</label>
                <input type="text" class="form-control" id="id_enquiry_name" name="enquiry_name" placeholder="*Required*">
            </div>
            <div class="col-md-6">
                <label for="id_enquiry_email" class="form-label">EMAIL:</label>
                <input type="email" class="form-control" id="id_enquiry_email" name="enquiry_email" placeholder="*Required*">
            </div>
            <div class="col-md-6">
                <label for="id_enquiry_company" class="form-label">Company:</label>
                <input type="text" class="form-control" id="id_enquiry_company" name="enquiry_company">
            </div>
            <div class="col-md-6">
                <label for="id_enquiry_occasion" size="5" class="form-label">Occasion:</label>
                <select id="id_enquiry_occasion" class="form-select" name="enquiry_occasion">
                    {% for selection, choice in form.enquiry_occasion.field.choices %}
                        <option value="{{ selection }}">{{ choice }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-6">
                <label for="id_enquiry_location" size="4" class="form-label">Preferred Location:</label>
                <select id="id_enquiry_location" class="form-select" name="enquiry_location">
                    {% for selection, choice in form.enquiry_location.field.choices %}
                        <option value="{{ selection }}">{{ choice }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-6">
                <label for="id_enquiry_theme" size="2" class="form-label">Preferred Theme:</label>
                <select id="id_enquiry_theme" class="form-select" name="enquiry_theme">
                    {% for selection, choice in form.enquiry_theme.field.choices %}
                        <option value="{{ selection }}">{{ choice }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-8">
                <label for="id_enquiry_when" class="form-label">PREFERRED DATE & TIME:</label>
                <input type="datetime-local" class="form-control" id="id_enquiry_when" name="enquiry_when"
                    placeholder="*Required - Choose preferred date & time">
            </div>
            <div class="range col-md-8">
                <label for="id_enquiry_number_of_quizzers" class="form-label" step="any">
                    Number of participants:
                    <div class="slider-value" id="range-value"></div>
                </label>
                <input type="range" class="form-range" min="15" max="120" value="15" step="5" id="id_enquiry_number_of_quizzers" name="enquiry_number_of_quizzers">
            </div>
            <div class="col-md-8">
                <label for="id_enquiry_description" class="form-label">Description:</label>
                <textarea class="form-control" id="id_enquiry_description" rows="5" name="enquiry_description"
                    placeholder="Please add any extra information here (max 1000 characters)">
                </textarea>
            </div>
            <div class="enquiry-btns col-6">
                <button type="reset" class="btn-clear">Clear Form</button>
                <button type="submit" class="btn-send">Send Enquiry</button>
            </div>
        </div>
        <div class="form-errors">
            {% if error %}
                <p class="error">{{ form.field_name.errors }}</p>
            {% endif %}
        </div>
    </form>
</div>
    
    <script>
        const rangeInput = document.getElementById('id_enquiry_number_of_quizzers');
        const rangeValue = document.getElementById('range-value');

        rangeInput.addEventListener('input', function () {
            rangeValue.textContent = rangeInput.value;
        });
    </script>
    <script>
        flatpickr("#id_enquiry_when", {
            enableTime: true,
            time_24hr: true,
            minuteIncrement: 15,
            minDate: "today",
            minTime: "12:00",
            maxTime: "22:00",
            dateFormat: "Y-m-d\\TH:i",
        });
    </script>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const locationLimit = document.getElementById("id_booking_location");
            const slider = document.getElementById("id_booking_number_of_quizzers");

            const setLimits = {
                "TS": { min: 12, max: 20 },
                "WP": { min: 20, max: 100 },
            };

            locationLimit.addEventListener("change", function () {
                const selectedLocation = this.value;
                const limits = setLimits[selectedLocation];

                if (limits) {
                    slider.min = limits.min;
                    slider.max = limits.max;

                    if (slider.value < limits.min || slider.value > limits.max) {
                        slider.value = limits.min;
                    }
                } else {
                    slider.min = 10;
                    slider.max = 150;
                    slider.value = 50;
                }
            });
        });
    </script>
    
{% endblock %}